### PR TITLE
Fixing the code to work under SDK 0.9.4

### PR DESCRIPTION
**Pull request by cherts**
1. Fixing the code to work under SDK 0.9.4
2. Added correct init WiFi module procedure.

Signed-off-by: Mikhail Grigorev sleuthhound@gmail.com

### CODE REVIEW

**Comment by elektronika-ba** [comment]
Mikhail, I haven't forgotten about your work. I am currently busy with Android app for CTRL project, and still didn't download SDK 0.9.4 to test against. I hope I will have time soon!

**Comment by CHERTS** [comment]
No problem, i'll wait as you need.

**Comment by CHERTS** [comment]
App for Android will be as open source?

**Comment by elektronika-ba** [comment]
Yes of corse!

**Pull request merged**
